version: '3.7'

services:
  app:
    build: .
    volumes:
      - '.:/usr/src/app'
      - 'pacakge_data:/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    command: npm run dev

volumes:
  pacakge_data: {}
